<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'SimpleLogger' => array($vendorDir . '/fguillot/simpleLogger/src'),
);
