<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit845ef4e25f6d07812123ab973c1351f7
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\Log\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
    );

    public static $prefixesPsr0 = array (
        'S' => 
        array (
            'SimpleLogger' => 
            array (
                0 => __DIR__ . '/..' . '/fguillot/simpleLogger/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit845ef4e25f6d07812123ab973c1351f7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit845ef4e25f6d07812123ab973c1351f7::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit845ef4e25f6d07812123ab973c1351f7::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
